version: '3'

services:
  sut:
    image: golang:1.12-alpine
    command: sh -c 'apk add --no-cache build-base git && go test -v'
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CGO_ENABLED=0
      - DB_CONNSTR=postgres://postgres@db/postgres?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
