version: '3'

services:
  api:
    image: golang:1.12-alpine
    command: sh -c 'apk add --no-cache git && go run main.go'
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CGO_ENABLED=0
      - DB_CONNSTR=postgres://postgres@db/postgres?sslmode=disable
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
